name: api_client
description: A Dart API Client for the  APIs (Pure Dart package).
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  http: ^0.13.4
  equatable: ^2.0.3
  foundation_flutter: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  lints: ^2.0.0
  test: ^1.21.1
